In [1]:
import mir_eval
import numpy as np
import os
import pandas as pd
import sys

sys.path.append("../src")
import localmodule

In [15]:
data_dir = "/Users/vl238/spl2017_data"
dataset_name = localmodule.get_dataset_name()
annotations_name = "_".join([dataset_name, "annotations"])
annotations_dir = os.path.join(data_dir, annotations_name)
predictions_name = "_".join([dataset_name, "baseline-predictions"])
predictions_dir = os.path.join(data_dir, predictions_name)
units = localmodule.get_units()
folds = localmodule.fold_units()
n_folds = len(folds)
n_thresholds = 100

fold_id = 0
# for fold_id in range(n_folds):
fold = folds[fold_id]
test_units, training_units, val_units = fold[0], fold[1], fold[2]
unit_minima = []
unit_maxima = []
for unit_str in training_units+val_units:
    prediction_name = unit_str + ".npy"
    prediction_path = os.path.join(predictions_dir, prediction_name)
    prediction_matrix = np.load(prediction_path)
    odf = prediction_matrix[:, 1]
    unit_min = np.min(odf)
    unit_minima.append(unit_min)
    unit_max = np.max(odf)
    unit_maxima.append(unit_max)
minima = min(unit_minima)
maxima = max(unit_maxima)
thresholds = np.linspace(minima, maxima, n_thresholds)

In [34]:
x = np.array([0.0, 3.0, 4.0, 4.1, 3.9, 3.8, 3.1])



array([3])

In [36]:

timestamps = prediction_matrix[:, 0]
annotation_path = os.path.join(annotations_dir, unit_str + ".txt")
df = pd.read_csv(annotation_path, "\t")

In [33]:
locations

(array([3]),)

In [30]:
x

array([ 0. ,  3. ,  4. ,  4.1,  3.9,  3.8,  3.1])